<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="2" skipped="0" tests="4" time="1.086" timestamp="2025-06-05T21:24:54.640150-05:00" hostname="DmytroPalii"><testcase classname="test.test_marks" name="test_1" time="0.020" /><testcase classname="test.test_marks" name="test_2" time="0.002" /><testcase classname="test.test_marks" name="test_3" time="0.002"><failure message="assert False">@mark.smoke
    def test_3():
&gt;       assert False
E       assert False

test\test_marks.py:16: AssertionError</failure></testcase><testcase classname="test.test_marks" name="test_4" time="0.796"><failure message="assert False">@mark.smoke
    def test_4():
&gt;       assert False
E       assert False

test\test_marks.py:21: AssertionError</failure></testcase></testsuite></testsuites>